name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run parser tests
        run: make run-parser-tests

      - name: Run instructions tests
        run: make run-instructions-tests

      - name: Run compiler tests
        run: make run-compiler-tests
